version: '3'

services:
  dash-web:
      image: imperialsys/dash-bonds:0.8
      restart: unless-stopped
      container_name: comparative-web
      ports:
        - "8080:5000"
      volumes:
        - ./config.py:/app/config.py
